# Generated by Django 4.2.1 on 2025-08-28 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('heslo', models.CharField(max_length=128)),
                ('overeno', models.BooleanField(default=False)),
                ('kod', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
