# Generated by Django 4.2.1 on 2025-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaznam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('zprava', models.TextField()),
                ('datum_cas', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
