# Generated by Django 4.2.1 on 2025-07-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ukol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField(blank=True)),
                ('termin', models.DateField(blank=True, null=True)),
                ('priorita', models.CharField(choices=[('N', 'Nízká'), ('S', 'Střední'), ('V', 'Vysoká')], default='N', max_length=1)),
                ('hotovo', models.BooleanField(default=False)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
