# Generated by Django 4.2.1 on 2025-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukol',
            name='kategorie',
            field=models.CharField(choices=[('skola', 'Škola'), ('prace', 'Práce'), ('osobni', 'Osobní')], default='osobni', max_length=10),
        ),
    ]
